### ISSUE TITLE
password character escape

### ISSUE THREAD

**Issue by Morpheus-ro** [Ardakilic/backmeup#1]
If you have a password with "!" or other character this is not working. How about you escape the $DBPASSWORD inside the backtick?

**Comment by Ardakilic** [comment]
Hey @Morpheus-ro ,

Can you please try this?

Open the .sh file

Find this:

```
-p$DBPASSWORD
```

Change as:

```
-p "$DBPASSWORD"
```

And try again.

Also please let me know whether this works.

**Comment by Morpheus-ro** [comment]
hei, thank you for the reply, the issue is not doing anything. I posted around so solve this issue -> http://unix.stackexchange.com/questions/349521/bash-escape-exclamation-character-inside-variable-with-backtick?noredirect=1#comment618641_349521 and here http://stackoverflow.com/questions/42628841/bash-escape-exclamation-character-inside-variable-with-backtick

**Comment by Morpheus-ro** [comment]
this is the modified line 
databases=\`mysql -h$DBHOST -u$DBUSER -p "$DBPASSWORD" -e "SHOW DATABASES;" | tr -d "| " | grep -v Database\`

**Comment by Ardakilic** [comment]
Hello again,

So can you confirm, changing `-p$DBPASSWORD` to `-p "$DBPASSWORD"` solves it for the time being ? I'll double quote the variables in mysql string on that case.

I checked those stackexchange links, I'll try to implement those feature soon, however, **while the query is running** even with those `mktemp` trick I can see the location of temp file, `cat` it and get the password through it. So no difference between `ps` trick and that. Please correct me if I'm wrong.

One way to prevent that is to put it somewhere only readable by root. I'll work on that in the future.

**Comment by Morpheus-ro** [comment]
Hey,

No, it is not solving the issue. I also tied `-p '$DBPASSWORD'` and is the tame result. Inside the backticks is the issue, I don't know hot to escape inside them. I tried also:

- `-p "'$DBPASSWORD'"`
- `-p \\"'$DBPASSWORD\\"`
- `-p \\"'$DBPASSWORD'\\"`

and nothing. is the same result, not working.

Regarding the security of the script, for me is not mandatory because I am using private networks and limited access to instances so that is not my primary concern now. The objective is to be able to export the tables from the DB with any kind of passwords and this is failing now.

**Comment by techsailor** [comment]
@Ardakilic Your documentation is slightly incorrect which is probably causing the issue for @Morpheus-ro and @Morpheus-ro you are not describing exactly what you are doing and have assumed there is a problem with the script. Let me explain.

You have given 2 examples under the section *On The Fly Configuration* the first example is incorrect because the password is not quoted.

@Morpheus-ro You do not show your command line (neither here nor at stackexchange)

Bug in the script : lines 170 and 174 should use double quotes around any variable that might contain characters which interfere with bash.

Just a comment, @Ardakilic instead of using the back-tick syntax for setting a variable to output of command, I would use `$( )` syntax, it's easier to read - although it doesn't make any difference.

I have created a [pull request](https://github.com/Ardakilic/backmeup/issues/2), which fixes this issue.

**Comment by Ardakilic** [comment]
@techsailor thank you for the PR!

Also, backtick is only used to define the backup name, anywhere else you're suggesting ?

**Comment by Ardakilic** [comment]
Closing this issue as a result of last PR. Yet, it's still open for discussion.
